"""Seed books + book_categories — 25 books from src/data/mockBooks.ts.
Book.id = ISBN (the primary key). No separate isbn column.
"""
from sqlalchemy.orm import Session

from app.models.book import Book
from app.models.book_category import BookCategory
from app.models.category import Category

# cover() equivalent: placehold.co URL matching frontend mock
def _cover(bg: str, text: str, label: str) -> str:
    import urllib.parse
    return f"https://placehold.co/200x280/{bg}/{text}?text={urllib.parse.quote(label)}"


BOOKS = [
    # ── Recommended for You ────────────────────────────────────────────────
    {
        "id": "978-81-000001-0-1",
        "title": "The Art of Focus",
        "author_id": "a1",
        "publisher": "Mind Publishers",
        "format": "Paperback",
        "categories": ["Non-fiction", "Self Help"],
        "price": 399,
        "cover_image": _cover("f59e0b", "1a1a1a", "The Art of Focus"),
        "synopsis": "Practical guide to mastering focus & boosting productivity every day.",
        "back_cover_text": "In The Art of Focus, Arjun Patel guides you through battle-tested strategies to eliminate distraction, build laser-sharp concentration, and achieve more in less time.",
        "language": "English",
        "rating": 4.5,
        "sells": 1230,
        "featured": True,
    },
    {
        "id": "978-81-000001-0-2",
        "title": "The Art of Learning",
        "author_id": "a2",
        "publisher": "Insight Books",
        "format": "Paperback",
        "categories": ["Non-fiction", "Self Help"],
        "price": 259,
        "cover_image": _cover("f97316", "ffffff", "The Art of Learning"),
        "synopsis": "Master the mindset and methods for effective lifelong learning.",
        "back_cover_text": "Raj Patel reveals the science of accelerated learning and how to apply it to every area of your life, from new skills to complex subjects.",
        "language": "English",
        "rating": 4.3,
        "sells": 980,
        "featured": True,
    },
    {
        "id": "978-81-000001-0-3",
        "title": "The Path to Success",
        "author_id": "a3",
        "publisher": "Summit Press",
        "format": "Paperback",
        "categories": ["Non-fiction", "Self Help"],
        "price": 359,
        "cover_image": _cover("0ea5e9", "ffffff", "The Path to Success"),
        "synopsis": "A practical guide to achieving goals with clarity and confidence.",
        "back_cover_text": "James Wright distills decades of business experience into a clear roadmap for professional success, personal fulfilment, and lasting happiness.",
        "language": "English",
        "rating": 4.2,
        "sells": 870,
        "featured": True,
    },
    {
        "id": "978-81-000001-0-4",
        "title": "Deep Work Mastery",
        "author_id": "a1",
        "publisher": "Mind Publishers",
        "format": "eBook",
        "categories": ["Non-fiction", "Business"],
        "price": 199,
        "cover_image": _cover("7c3aed", "ffffff", "Deep Work Mastery"),
        "synopsis": "Rules for focused success in a distracted world.",
        "back_cover_text": "Deep work — the ability to focus without distraction — is becoming increasingly rare and valuable. This book shows you how to cultivate it.",
        "language": "English",
        "rating": 4.6,
        "sells": 1100,
        "featured": True,
    },
    # ── Bestsellers this Month ───────────────────────────────────────────────
    {
        "id": "978-81-000001-0-5",
        "title": "The Midnight Hour",
        "author_id": "a4",
        "publisher": "Dark Lane Books",
        "format": "Paperback",
        "categories": ["Fiction", "Thriller", "Horror"],
        "price": 299,
        "cover_image": _cover("1e293b", "94a3b8", "The Midnight Hour"),
        "synopsis": "Haunting tale of a man's journey & the shadows of a forgotten past.",
        "back_cover_text": "When retired detective Marcus Cole receives an anonymous letter referencing a cold case he thought was closed forever, he is drawn back into a web of secrets that threatens everything he holds dear.",
        "language": "English",
        "rating": 4.7,
        "sells": 2100,
        "bestseller": True,
    },
    {
        "id": "978-81-000001-0-6",
        "title": "Beneath the Stars",
        "author_id": "a5",
        "publisher": "Heartfelt Press",
        "format": "Hard Cover",
        "categories": ["Fiction", "Love", "Drama"],
        "price": 499,
        "cover_image": _cover("be123c", "fce7f3", "Beneath the Stars"),
        "synopsis": "A heartwarming tale, where two souls discover who you need.",
        "back_cover_text": "A chance encounter on a rainy night leads two strangers on an unforgettable journey across the country — and into each other's hearts.",
        "language": "English",
        "rating": 4.4,
        "sells": 1850,
        "bestseller": True,
    },
    {
        "id": "978-81-000001-0-7",
        "title": "The Final Frontier",
        "author_id": "a6",
        "publisher": "Cosmos Books",
        "format": "Paperback",
        "categories": ["Fiction", "Thriller", "Science Fiction"],
        "price": 359,
        "cover_image": _cover("0f172a", "38bdf8", "The Final Frontier"),
        "synopsis": "A mission to space secrets to change humanity forever.",
        "back_cover_text": "Astronaut Dr. Priya Sharma uncovers evidence of an alien artefact buried on the dark side of the moon — and discovers that some secrets are worth dying for.",
        "language": "English",
        "rating": 4.5,
        "sells": 1650,
        "bestseller": True,
    },
    {
        "id": "978-81-000001-0-8",
        "title": "Shadows of Tomorrow",
        "author_id": "a4",
        "publisher": "Dark Lane Books",
        "format": "Paperback",
        "categories": ["Fiction", "Mystery", "Thriller"],
        "price": 279,
        "cover_image": _cover("292524", "e7e5e4", "Shadows of Tomorrow"),
        "synopsis": "A tense thriller where the past and present collide.",
        "back_cover_text": "A journalist investigating a series of disappearances realises she may be the next target in a game she cannot afford to lose.",
        "language": "English",
        "rating": 4.3,
        "sells": 1200,
        "bestseller": True,
    },
    # ── New Launches ─────────────────────────────────────────────────────────
    {
        "id": "978-81-234-5678-9",
        "title": "The Joy of Minimalism",
        "author_id": "a7",
        "publisher": "Clarity House",
        "format": "Paperback",
        "categories": ["Non-fiction", "Self Help"],
        "price": 149,
        "cover_image": _cover("fbbf24", "1c1917", "The Joy of Minimalism"),
        "synopsis": "Declutter your life to uncover peace, clarity, and joy.",
        "back_cover_text": "In The Joy of Minimalism, Daniel Reed guides you through practical strategies to declutter your mind, space, and schedule.",
        "language": "English",
        "rating": 4.6,
        "sells": 145,
        "new_launch": True,
    },
    {
        "id": "978-81-000001-1-0",
        "title": "The Vanishing House",
        "author_id": "a8",
        "publisher": "Eerie Press",
        "format": "eBook",
        "categories": ["Fiction", "Horror", "Mystery"],
        "price": 99,
        "cover_image": _cover("164e63", "cffafe", "The Vanishing House"),
        "synopsis": "A chilling mystery unfolds within a house that disappears.",
        "back_cover_text": "The Hargrove family moves into their dream home — only to discover the house has a mind of its own.",
        "language": "English",
        "rating": 4.1,
        "sells": 88,
        "new_launch": True,
    },
    {
        "id": "978-81-000001-1-1",
        "title": "The Lost Kitten",
        "author_id": "a9",
        "publisher": "Little Wonders",
        "format": "Hard Cover",
        "categories": ["Fiction", "Children's"],
        "price": 339,
        "cover_image": _cover("f97316", "fff7ed", "The Lost Kitten"),
        "synopsis": "A heartwarming tale of courage, friendship, and feline adventure.",
        "back_cover_text": "When little Mia's kitten goes missing, she embarks on a neighbourhood adventure that teaches her about bravery, kindness, and the true meaning of home.",
        "language": "English",
        "rating": 4.8,
        "sells": 62,
        "new_launch": True,
    },
    {
        "id": "978-81-000001-1-2",
        "title": "Echoes of Eternity",
        "author_id": "a5",
        "publisher": "Heartfelt Press",
        "format": "Paperback",
        "categories": ["Romance", "Fiction", "Drama"],
        "price": 289,
        "cover_image": _cover("db2777", "fdf2f8", "Echoes of Eternity"),
        "synopsis": "A sweeping romance across two continents and one lifetime.",
        "back_cover_text": "From the cobblestone streets of Paris to the beaches of Goa, two hearts separated by circumstance find each other again — and again.",
        "language": "English",
        "rating": 4.3,
        "sells": 55,
        "new_launch": True,
    },
    # ── Additional catalogue books ────────────────────────────────────────────
    {
        "id": "978-81-000001-1-3",
        "title": "Star Child",
        "author_id": "a6",
        "publisher": "Cosmos Books",
        "format": "Paperback",
        "categories": ["Science Fiction", "Fiction"],
        "price": 329,
        "cover_image": _cover("0c4a6e", "bae6fd", "Star Child"),
        "synopsis": "A young girl discovers she was born among the stars.",
        "back_cover_text": "When twelve-year-old Zara finds a glowing stone in her backyard, she begins a journey that will take her to the far reaches of the galaxy — and back home again.",
        "language": "English",
        "rating": 4.4,
        "sells": 430,
    },
    {
        "id": "978-81-000001-1-4",
        "title": "The Dragon Queen",
        "author_id": "a5",
        "publisher": "Mythic Tales",
        "format": "Hard Cover",
        "categories": ["Fantasy", "Fiction"],
        "price": 549,
        "cover_image": _cover("7f1d1d", "fca5a5", "The Dragon Queen"),
        "synopsis": "An epic fantasy of power, betrayal, and redemption.",
        "back_cover_text": "Raised as a slave, Kira discovers she carries royal blood — and the power to command dragons.",
        "language": "English",
        "rating": 4.7,
        "sells": 780,
    },
    {
        "id": "978-81-000001-1-5",
        "title": "The Forgotten War",
        "author_id": "a4",
        "publisher": "Historia Press",
        "format": "Paperback",
        "categories": ["Historical", "Fiction"],
        "price": 315,
        "cover_image": _cover("78350f", "fef3c7", "The Forgotten War"),
        "synopsis": "Untold stories from the frontlines of history.",
        "back_cover_text": "Drawing on declassified archives and first-hand accounts, this gripping historical novel follows four soldiers whose fates intertwined during a war the world tried to forget.",
        "language": "English",
        "rating": 4.5,
        "sells": 620,
    },
    {
        "id": "978-81-000001-1-6",
        "title": "My Bombay Cookbook",
        "author_id": "a7",
        "publisher": "Spice Road Books",
        "format": "Hard Cover",
        "categories": ["Cooking"],
        "price": 450,
        "cover_image": _cover("b45309", "fff7ed", "My Bombay Cookbook"),
        "synopsis": "100 authentic recipes from the streets of Mumbai.",
        "back_cover_text": "From vada pav to biryani, this beautifully illustrated cookbook brings the flavours of Mumbai into your kitchen with easy-to-follow recipes.",
        "language": "English",
        "rating": 4.6,
        "sells": 310,
    },
    {
        "id": "978-81-000001-1-7",
        "title": "Journey to the Himalayas",
        "author_id": "a8",
        "publisher": "Wanderlust Press",
        "format": "Paperback",
        "categories": ["Travel", "Memoir"],
        "price": 225,
        "cover_image": _cover("164e63", "ecfeff", "Journey to Himalayas"),
        "synopsis": "A solo trek through the world's highest mountains.",
        "back_cover_text": "Clara Nelson sets off alone into the Himalayas with nothing but a backpack and a journal. What she finds changes her forever.",
        "language": "English",
        "rating": 4.3,
        "sells": 190,
    },
    {
        "id": "978-81-000001-1-8",
        "title": "The Teenage Mind",
        "author_id": "a9",
        "publisher": "Youth Works",
        "format": "Paperback",
        "categories": ["Young Adult", "Fiction"],
        "price": 199,
        "cover_image": _cover("4f46e5", "e0e7ff", "The Teenage Mind"),
        "synopsis": "A coming-of-age story set in the digital age.",
        "back_cover_text": "Seventeen-year-old Anya is trying to figure out who she is while the whole world seems to be watching.",
        "language": "English",
        "rating": 4.2,
        "sells": 520,
    },
    {
        "id": "978-81-000001-1-9",
        "title": "The Laughing Buddha",
        "author_id": "a2",
        "publisher": "Inner Peace",
        "format": "Paperback",
        "categories": ["Philosophy", "Religion"],
        "price": 175,
        "cover_image": _cover("065f46", "d1fae5", "The Laughing Buddha"),
        "synopsis": "Ancient wisdom for a modern restless world.",
        "back_cover_text": "Through parables and philosophy, Raj Patel distils centuries of Eastern wisdom into practical daily guidance for a calmer, more purposeful life.",
        "language": "English",
        "rating": 4.4,
        "sells": 340,
    },
    {
        "id": "978-81-000001-2-0",
        "title": "Code the World",
        "author_id": "a3",
        "publisher": "TechStart",
        "format": "eBook",
        "categories": ["Science", "Non-fiction"],
        "price": 129,
        "cover_image": _cover("1d4ed8", "dbeafe", "Code the World"),
        "synopsis": "How software is reshaping civilisation.",
        "back_cover_text": "A sweeping look at how code has transformed every corner of modern life — from medicine to democracy — and what comes next.",
        "language": "English",
        "rating": 4.5,
        "sells": 660,
    },
    {
        "id": "978-81-000001-2-1",
        "title": "The Silent Verse",
        "author_id": "a8",
        "publisher": "Verse & Voice",
        "format": "Paperback",
        "categories": ["Poetry", "Drama"],
        "price": 149,
        "cover_image": _cover("581c87", "f3e8ff", "The Silent Verse"),
        "synopsis": "A collection of poems about love, loss, and longing.",
        "back_cover_text": "Haunting and beautiful, The Silent Verse gathers sixty poems that explore the full spectrum of human emotion with rare honesty and grace.",
        "language": "English",
        "rating": 4.1,
        "sells": 120,
    },
    {
        "id": "978-81-000001-2-2",
        "title": "Learn Spanish in 30 Days",
        "author_id": "a2",
        "publisher": "LinguaFast",
        "format": "Paperback",
        "categories": ["Language Learning"],
        "price": 299,
        "cover_image": _cover("dc2626", "fee2e2", "Learn Spanish"),
        "synopsis": "Conversational Spanish for absolute beginners.",
        "back_cover_text": "Using the proven spaced-repetition method, this programme has helped over 500,000 learners hold their first Spanish conversation in just thirty days.",
        "language": "English",
        "rating": 4.0,
        "sells": 810,
    },
    {
        "id": "978-81-000001-2-3",
        "title": "Wings of Steel",
        "author_id": "a9",
        "publisher": "Brave Hearts",
        "format": "Hard Cover",
        "categories": ["Biography", "Non-fiction"],
        "price": 399,
        "cover_image": _cover("0f766e", "ccfbf1", "Wings of Steel"),
        "synopsis": "The life of India's first female fighter pilot.",
        "back_cover_text": "From a small village in Rajasthan to the cockpit of a MiG-21, this biography traces the extraordinary journey of Wing Commander Meera Singh.",
        "language": "English",
        "rating": 4.8,
        "sells": 570,
    },
    {
        "id": "978-81-000001-2-4",
        "title": "Graphic Universe",
        "author_id": "a6",
        "publisher": "Panel Press",
        "format": "Hard Cover",
        "categories": ["Comics & Graphic Novels", "Science Fiction"],
        "price": 495,
        "cover_image": _cover("312e81", "c7d2fe", "Graphic Universe"),
        "synopsis": "A graphic novel about the birth of the cosmos.",
        "back_cover_text": "Told entirely in stunning illustrations, Graphic Universe takes you from the Big Bang to the far future in a visual feast that is equal parts science and art.",
        "language": "English",
        "rating": 4.6,
        "sells": 280,
    },
    {
        "id": "978-81-000001-2-5",
        "title": "The Business of Us",
        "author_id": "a3",
        "publisher": "Summit Press",
        "format": "Paperback",
        "categories": ["Business", "Non-fiction", "Biography"],
        "price": 379,
        "cover_image": _cover("166534", "dcfce7", "The Business of Us"),
        "synopsis": "How great companies are built by great teams.",
        "back_cover_text": "James Wright reveals the hidden ingredient in every high-performing business: the quality of relationships between the people who drive it.",
        "language": "English",
        "rating": 4.4,
        "sells": 740,
    },
]


def seed_books(db: Session) -> None:
    for data in BOOKS:
        categories = data.pop("categories")
        book_id = data["id"]

        if not db.get(Book, book_id):
            db.add(Book(**data))
            db.flush()  # so the book row exists before adding categories

        # Seed BookCategory join rows
        for cat_name in categories:
            cat = db.query(Category).filter_by(name=cat_name).first()
            if cat:
                from app.models.book_category import BookCategory  # noqa: PLC0415
                exists = db.query(BookCategory).filter_by(book_id=book_id, category_id=cat.id).first()
                if not exists:
                    db.add(BookCategory(book_id=book_id, category_id=cat.id))

    db.commit()
    print(f"[seed] books: {len(BOOKS)} seeded")
